Update paphos info
redbrick/docs-old pull request #10
Opened 2017-04-09 22:57 UTC by gruunday

2017-04-10 06:10 UTC, butlerx requested changes
@zergless what services am i forgetting

2017-04-10 06:10 UTC, butlerx commented on docs/machines/paphos.md
> +* Mail Server
- ldap
 - dns
 - list

2017-04-10 11:55 UTC, zergless commented on docs/machines/paphos.md
> +* Mail Server
mailing lists instead of just list pls

2017-04-11 08:15 UTC, butlerx requested changes

2017-04-11 08:15 UTC, butlerx commented on docs/machines/paphos.md
> +* Mail Server
could you change mail server so its 
- Mail
  - exim
  - dovecoat

2017-04-11 08:15 UTC, butlerx commented on docs/machines/paphos.md
> +* Mail Server
also icecast and boards runs on paphos could you also link these to their entries

2017-04-11 09:09 UTC, zergless commented
I think you got most of them

2017-04-11 14:14 UTC, butlerx commented on docs/machines/paphos.md
> +    - dovecoat
why not link dovecoat?

2017-04-11 14:15 UTC, gruunday commented on docs/machines/paphos.md
> +    - dovecoat
Can't find a doc entry for it. But then again am tired

2017-04-11 14:16 UTC, butlerx commented on docs/machines/paphos.md
> +    - dovecoat
services/dovecot

2017-04-11 14:19 UTC, gruunday commented on docs/machines/paphos.md
> +    - dovecoat
huh well

2017-04-11 14:31 UTC, butlerx commented on docs/machines/paphos.md
> +* [dns](/services/bind9)
is bind not in netwrok

2017-04-11 14:32 UTC, VoyTechnology commented on docs/machines/paphos.md
> +* [dns](/services/bind9)
It is unless #12 is merged

2017-04-11 14:36 UTC, gruunday commented on docs/machines/paphos.md
> +* [dns](/services/bind9)
Well until that one is resolved i'll leave this here

2017-04-11 14:37 UTC, butlerx commented on docs/machines/paphos.md
> +* [dns](/services/bind9)
#12 is not merged and still in discussion

2017-04-12 12:50 UTC, butlerx approved these changes

2017-04-12 14:43 UTC, merged