Update git.md
redbrick/docs-old pull request #110
Opened 2019-10-09 16:37 UTC by herronk2

2019-10-09 16:44 UTC, m1cr0man requested changes
Wrong host

2019-10-09 16:44 UTC, m1cr0man commented on docs/services/git.md
> +We run Gitea on daedalus which runs NixOS. The config can be found [here](https://git.redbrick.dcu.ie/m1cr0man/nix-configs-rb/src/branch/master/services/gitea.nix).
Nope, gitea runs on hardcase.

2019-10-21 13:02 UTC, theycallmemac commented
@herronk2 if you are at hackerclub this wednesday we can update your PR - otherwise I'll close this and get someone else to make the change!

2019-10-25 18:47 UTC, m1cr0man commented
Hey I have totally overhauled the git docs now and they reflect the current state. This PR is superseded now.

2019-10-25 20:32 UTC, closed without merging