Update ldap.md
redbrick/docs-old pull request #111
Opened 2019-10-09 16:41 UTC by byAdam

2019-10-09 16:43 UTC, m1cr0man requested changes
Needs more info

2019-10-09 16:43 UTC, m1cr0man commented on docs/services/ldap.md
> +- Primary LDAP Runs on daedalus.internal
It should be highlighted also that:
- icarus.internal is slaved to it
- Both are deployed via NixOS

2019-10-10 11:46 UTC, theycallmemac commented on docs/services/ldap.md
> +- Primary LDAP Runs on daedalus.internal
Secondary server can be said to be icarus.internal so?

2019-10-10 14:17 UTC, m1cr0man commented on docs/services/ldap.md
> +- Primary LDAP Runs on daedalus.internal
Well, no because it's not "secondary" from a fail over POV. It requires a manual DNS switch.

2019-10-21 13:01 UTC, theycallmemac commented on docs/services/ldap.md
> +- Primary LDAP Runs on daedalus.internal
Has this changed since the weekend @m1cr0man ? Is it worth adding ldap2.internal?

2019-10-21 21:02 UTC, m1cr0man commented
I have opened a new PR to rewrite most of these docs, closing this PR

2019-10-21 21:02 UTC, closed without merging