update services moved onto hardcase and removed services
redbrick/docs-old pull request #134
Opened 2020-02-21 21:34 UTC by theycallmemac

Updating some information on the follow:

- services/gitea
- services/paste

Removing information on:

- web/pubcookie
- web/apachemodules

2020-02-22 01:17 UTC, butlerx commented on docs/services/git.md
> +- SSH is set to `10022` because otherwise it would clash with the host's real SSH.
This was actually disabled in the migrations to nix.

2020-02-22 01:17 UTC, butlerx commented on docs/services/paste.md
> +Redbrick currently uses m1cr0man's fork of [Privatebin](https://github.com/m1cr0man/PrivateBin) as a paste utility.
Did we not just switch back from the fork?

2020-02-22 12:43 UTC, theycallmemac commented on docs/services/git.md
> +- SSH is set to `10022` because otherwise it would clash with the host's real SSH.
I'll remove the SSH point then, thanks.

2020-02-22 12:44 UTC, theycallmemac commented on docs/services/paste.md
> +Redbrick currently uses m1cr0man's fork of [Privatebin](https://github.com/m1cr0man/PrivateBin) as a paste utility.
https://github.com/redbrick/nix-configs/blob/master/packages/privatebin/default.nix

Still uses the fork.

2020-02-22 12:44 UTC, butlerx commented on docs/services/paste.md
> +Redbrick currently uses m1cr0man's fork of [Privatebin](https://github.com/m1cr0man/PrivateBin) as a paste utility.
cool

2020-02-23 16:32 UTC, butlerx commented on docs/services/paste.md
> +Redbrick currently uses m1cr0man's fork of [Privatebin](https://github.com/m1cr0man/PrivateBin) as a paste utility.
https://github.com/redbrick/nix-configs/pull/39 will switch back to upstream

2020-02-24 00:33 UTC, theycallmemac commented
CI failing due to an exception cropping up during the pip install phase

2020-03-14 18:42 UTC, m1cr0man requested changes
Looks good juts the bit about the privatebin fork needs to change

2020-03-14 18:42 UTC, m1cr0man commented on docs/services/paste.md
> +Redbrick currently uses m1cr0man's fork of [Privatebin](https://github.com/m1cr0man/PrivateBin) as a paste utility.
Yep this is merged now

2020-03-25 20:16 UTC, m1cr0man submitted a review, later dismissed

2020-07-11 13:18 UTC, butlerx submitted a review, later dismissed

2020-07-11 13:21 UTC, butlerx approved these changes

2020-07-11 13:58 UTC, m1cr0man approved these changes

2020-07-11 13:58 UTC, merged