replace fluentd with promtail
redbrick/docs-old pull request #135
Opened 2020-02-23 18:18 UTC by butlerx

2020-02-24 00:26 UTC, theycallmemac submitted a review, later dismissed
Some of this is subject to change in the next few months but as of now this is good. Merging

2020-02-24 00:27 UTC, theycallmemac commented
Actually, @butlerx why is the CI broken on this?

2020-02-24 00:33 UTC, theycallmemac commented
Nvm just checked there, looks to be an exception cropping up during the pip install.

2020-03-14 18:45 UTC, m1cr0man requested changes

2020-03-14 18:45 UTC, m1cr0man commented on docs/index.md
> -- [RedBrick Apt Repo (work in progress)](/procedures/redbrick-apt)
You need to actually delete that procedure md

2020-03-14 18:45 UTC, m1cr0man commented on docs/index.md
> +https://docs.redbrick.dcu.ie and https://redbrick.rtfd.io
Can we make these actual links? :)

2020-03-17 16:34 UTC, butlerx commented on docs/index.md
> +https://docs.redbrick.dcu.ie and https://redbrick.rtfd.io
done

2020-03-17 16:34 UTC, butlerx commented on docs/index.md
> -- [RedBrick Apt Repo (work in progress)](/procedures/redbrick-apt)
done

2020-03-17 16:34 UTC, butlerx commented
@theycallmemac fixed tests

2020-07-11 13:57 UTC, m1cr0man approved these changes

2020-07-11 13:57 UTC, merged