updated networking
redbrick/docs-old pull request #161
Opened 2020-07-23 22:15 UTC by ylmcc

Updated the networking section with the following:

- How to configure LACP on the Cisco switches

- How to source nat or do destination nat on our SRX. 

- Brief topology of Redbrick network

2020-07-23 22:43 UTC, m1cr0man requested changes
Looks good! Spotted some grammar/spelling errors. Also the backticking and HTML line breaks need to be fixed/removed in the junos doc.

2020-07-23 22:43 UTC, m1cr0man commented on docs/network/topology.md
> +- Between Sebastian and the SRX due to unforeseen circumstances LACP between the two was never completed. However there is a router-on-a-stick is implementation in place.
"is implementation in place" -> "implemented in place"

2020-07-23 22:43 UTC, m1cr0man commented on docs/network/topology.md
> +Redbrick has a L2 fibre connection back to DCU's core that is connected on Sebastian's port fibre port.
`port fibre port` remove the first port?

2020-07-23 22:43 UTC, m1cr0man commented on docs/network/junos.md
> +``edit security nat destination``<br>
Yeah I would kill all the \<br>'s, and replace any double-backticks with full code blocks

2020-07-23 22:43 UTC, m1cr0man commented on docs/network/junos.md
> +Before saving your changes it is recommeneded to do the following command `` show | compare`` this will show you any configuration changes that have been made.
The double backticks should be changed to single backticks where they are inline with regular strings.

2020-07-23 22:43 UTC, m1cr0man commented on docs/network/junos.md
> +If you want to allow a specific machine to access the internet from within Redbrick you will need source NAT you will need to configure source NAT that will use a ``136.206.15.X/24`` address
Sentence doubled? "You will need source Nat you will need to configure source NAT"

2020-07-23 22:43 UTC, m1cr0man commented on docs/network/junos.md
> +Currently in Redbrick we are using a SRX 210 firewall. There is a router-on-a-stick setup between Sebastian and our SRX. This allows multiple VLANs to go over the link between Sebastian and the SRX.
Oh I thought it was a 220? hah.

2020-07-23 22:43 UTC, m1cr0man commented on docs/network/junos.md
> +Unlike Cisco you do not need to be in priviledge mode to view configuration. However as Junos runs FreeBSD you do need to have the correct priviledge level to access different hierachies of the Junos
priviledge -> remove the d on both accounts.

2020-07-23 22:43 UTC, m1cr0man commented on docs/network/junos.md
> +Unlike Cisco you do not need to be in priviledge mode to view configuration. However as Junos runs FreeBSD you do need to have the correct priviledge level to access different hierachies of the Junos
hiera**r**chies

2020-07-23 22:45 UTC, m1cr0man commented
One other request: Could you specify where to find the passwords for each device in the password safe? (What the name of the password is?)

2020-07-25 18:17 UTC, m1cr0man commented on docs/network/junos.md
> +``edit security nat source ruleset NAME_OF_RULESET``<br>
It's actually rule-set as I found out trying this :)

Also I would maybe indicate that using an existing ruleset might make sense, since we have that OUTBOUND rule set.

2020-10-21 20:29 UTC, ylmcc commented on docs/network/junos.md
> +Currently in Redbrick we are using a SRX 210 firewall. There is a router-on-a-stick setup between Sebastian and our SRX. This allows multiple VLANs to go over the link between Sebastian and the SRX.
You were correct, at the time I was configuring a SRX210

2020-10-21 20:31 UTC, m1cr0man approved these changes
All good now!

2020-10-21 22:12 UTC, m1cr0man commented
Merging now, I have a patch ready to fix the lint issues.

2020-10-21 22:12 UTC, merged

2020-10-22 09:22 UTC, butlerx commented on docs/network/networksetup.md
> -```graphviz
Why dropping the Graphiz, We support rendering these in the docs and easier to maintain code then png