Updatedoc
redbrick/docs-old pull request #34
Opened 2017-04-14 23:24 UTC by gruunday

2017-04-14 23:32 UTC, VoyTechnology commented
When merging can a better name be provided for the merge commit? Would be pretty hard to figure out what happened from the current name

2017-04-14 23:36 UTC, gruunday commented
@VoyTechnology  Yes apologizes

2017-04-14 23:38 UTC, gruunday commented
Not urgent. I am sure someone will double check in the morning

2017-04-15 05:52 UTC, butlerx requested changes
Php was also done

2017-04-15 08:58 UTC, butlerx commented on docs/plans/TODO-2017.md
> +    - [X] bitlbee
this is installed but user config needs to be moved and dns changed

2017-04-15 09:04 UTC, gruunday commented on docs/plans/TODO-2017.md
> +    - [X] bitlbee
I installed bitlbee last night.... was it already there? I installed a docker one with the facebook bitlbee too. Currently works

2017-04-15 09:07 UTC, butlerx commented on docs/plans/TODO-2017.md
> +    - [X] bitlbee
yes `/etc/docker-compose/services/bitlebee` it also worked with the fb plugin installed

2017-04-16 10:10 UTC, butlerx approved these changes

2017-04-16 10:11 UTC, merged