Bugfix/markdown
redbrick/docs-old pull request #56
Opened 2017-05-18 12:39 UTC by butlerx

2017-05-18 23:37 UTC, VoyTechnology commented on docs/network/mainaddressspace.md
> +![Network Diagram](/img/network-diagram171904.png)
Related to discussion on #61

2017-05-18 23:46 UTC, VoyTechnology requested changes

2017-05-18 23:46 UTC, VoyTechnology commented on docs/plans/project-ideas.md
> +  * I may look into this over the summer - creadak
`>` would be more appropiate?

2017-05-18 23:46 UTC, VoyTechnology commented on docs/plans/project-ideas.md
> +  * If you're doing this, you should hang around boards through one of the old fashioned interface
As per other discussion on `*` vs `-` on subpoints

2017-05-18 23:46 UTC, VoyTechnology commented on docs/plans/project-ideas.md
> +    helpdesk members. If I do it, it'll be in python - creadak
`>` for both?

2017-05-18 23:46 UTC, VoyTechnology commented on docs/procedures/mail_setup.md
> +status of the machines/Nigerian princes offering you vast sums of money. This comes with the
We are missing a section on hook-up requests

2017-05-18 23:48 UTC, butlerx commented on docs/procedures/mail_setup.md
> +status of the machines/Nigerian princes offering you vast sums of money. This comes with the
......what

2017-05-18 23:51 UTC, butlerx commented on docs/plans/project-ideas.md
> +  * I may look into this over the summer - creadak
can you have `>` in a list?

2017-05-19 00:17 UTC, butlerx commented on docs/plans/project-ideas.md
> +    helpdesk members. If I do it, it'll be in python - creadak
these dont mix well with -

2017-05-19 13:06 UTC, VoyTechnology approved these changes
LGTM

2017-05-19 13:27 UTC, merged