format procedures
redbrick/docs-old pull request #64
Opened 2017-05-18 22:00 UTC by butlerx

2017-05-18 22:21 UTC, VoyTechnology requested changes

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/dracaccess.md
> +Open [https://localhosy](https://localhost:443/) in your browser and you should have the requested
s/localhosy/localhost

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/modifyingldap.md
> +```ldif
I am not sure which one is intended. In other blocks there is a space between \`\`\` and `type`, but here there isn't. If that's a choice, I would prefer if there was no space, but if you think space is better, change this one to be consistent

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/rrs.md
> +./newyear_ldif.py < slapcat.pre-newyear > slapcat.pre-rrs
Start with `$`

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/rrs.md
> +ldapsearch -xLLL -y /etc/ldap.secret -D cn=root,ou=ldap,o=redbrick > rb.ldif
Start with `$`

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/rrs.md
> +slapcat -l slapcat.pre-newyear
Start with `$`

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/rrs.md
> +useradm unpaid_warn
Start with `$`

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/rrs.md
> +useradm pre_sync
Start with `$`

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/rrs.md
> +./make-rb-dcu-tree.sh
Start with `$`

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/rrs.md
> + cat slapcat.pre-rrs rb-dcu-tree.ldif > slapcat.pre-rrs-dcu
Start with `$`

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/rrs.md
> +slapadd -v -u -l slapcat.pre-rrs-dcu
Start with `$`

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/rrs.md
> +slapadd -v -l slapcat.pre-rrs-dcu
Start with `$`

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/rrs.md
> +> rrs.log
s/`>`/`$`

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/rrs.md
> +useradm create_uidNumber
Start with `$`

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/rrs.md
> +slapcat -l - | remove_dcutree_ldif.py > slapcat.rrs
Start both with `$`

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/rrs.md
> +/etc/init.d/exim stop
Start with `$`

2017-05-18 22:21 UTC, VoyTechnology commented on docs/procedures/useradm.md
> +# Useradm
Useradm should not be part of procedures. I realize  I have approved #45 which has added this to procedures but this should be in services, or part of `admin scripts` page in services

2017-05-18 22:21 UTC, VoyTechnology commented
There are more cases where `$` is needed at a start of the command

2017-05-18 22:23 UTC, VoyTechnology commented on docs/procedures/post_powercut.md
> +  * If LDAP is down, you'll need to use the ALOM to do the next step.
I am not sure is this the correct style for subpoints. I would prefer to use `-` in this case to help with readability.

2017-05-18 22:25 UTC, VoyTechnology commented on docs/procedures/post_powercut.md
> +  * Check that ldapclient started (svcs -xv). If it didn't, run **svcadm clear ldap/client** to make
This looks like a command. I believe instead of `**` it should be \`

2017-05-18 22:30 UTC, butlerx commented on docs/procedures/rrs.md
> +useradm create_uidNumber
im folllowing [md014](https://github.com/mivok/markdownlint/blob/master/docs/RULES.md#md014---dollar-signs-used-before-commands-without-showing-output) which i like which means only use $ is theres output aswell

2017-05-18 22:31 UTC, butlerx commented on docs/procedures/useradm.md
> +# Useradm
useradm is part of rrs, its literally a library in it

2017-05-18 22:32 UTC, butlerx commented on docs/procedures/rrs.md
> +> rrs.log
its not i dont knwo what `> rrs.log` is but its not a command

2017-05-18 22:36 UTC, butlerx commented on docs/procedures/modifyingldap.md
> +```ldif
what sapce?

2017-05-18 22:36 UTC, butlerx commented on docs/procedures/modifyingldap.md
> +```ldif
not a choice just how i typed it doesnt matter either way

2017-05-18 22:39 UTC, butlerx commented on docs/procedures/post_powercut.md
> +  * If LDAP is down, you'll need to use the ALOM to do the next step.
* and - are the same but i prefer - anyway

2017-05-18 22:39 UTC, VoyTechnology commented on docs/procedures/rrs.md
> +> rrs.log
STDIN?

2017-05-18 22:45 UTC, VoyTechnology approved these changes
I would still like to see `useradm` being out of procedures. You can move it to services in this PR if you want or I'll move it

2017-05-18 22:45 UTC, butlerx commented on docs/procedures/rrs.md
> +> rrs.log
maybe

2017-05-18 22:45 UTC, merged

2017-05-18 22:47 UTC, butlerx commented
this is about linting moveing rrs, useradm and c&s  day process to seperate entries can be done anothher time

2017-05-19 11:38 UTC, d-fens commented on docs/procedures/rrs.md
> +> rrs.log
```
true > rrs.log
:> rrs.log
> rrs.log
touch rrs.log
```

All the same. Just easier to type I guess.

2017-05-19 12:01 UTC, butlerx commented on docs/procedures/rrs.md
> +> rrs.log
TiL