add information about the pastebin instance.
redbrick/docs-old pull request #69
Opened 2017-05-30 18:02 UTC by AlexKraak

2017-05-30 19:01 UTC, butlerx requested changes
Just things to do with docker in general

2017-05-30 19:01 UTC, butlerx commented on docs/services/paste.md
> +FROM node:boron
Could we use boron-alpine?

2017-05-30 19:01 UTC, butlerx commented on docs/services/paste.md
> +    ports:
Could we give the image a nam

2017-05-31 23:54 UTC, butlerx commented on mkdocs.yml
> +    - Pastebin: services/paste.md
Paste should be before postgres

2017-06-07 20:04 UTC, AlexKraak commented on docs/services/paste.md
> +    ports:
the redis image?

2017-06-07 20:04 UTC, butlerx commented on docs/services/paste.md
> +    ports:
no the paste container

2017-06-07 20:05 UTC, butlerx commented on docs/services/paste.md
> +    ports:
just something like `image: redbrick/hastebin`

2017-06-07 20:26 UTC, butlerx approved these changes

2017-06-07 20:50 UTC, merged