updated hardware info
redbrick/docs-old pull request #86
Opened 2017-10-16 19:20 UTC by Sangreal8

2017-10-17 08:18 UTC, CSmartt requested changes

2017-10-17 08:18 UTC, CSmartt commented on docs/hardware/pygmalion.md
> +* CPU: Intel (R) Xeon (R) E5620 2.46GHz
2x of these

2017-10-17 08:18 UTC, CSmartt commented on docs/hardware/pygmalion.md
> +* Network: QLogic bnx2 Gigabit Ethernet Driver v2.2.6
`01:00.0 Ethernet controller: Broadcom Corporation NetXtreme II BCM5709 Gigabit Ethernet (rev 20)
01:00.1 Ethernet controller: Broadcom Corporation NetXtreme II BCM5709 Gigabit Ethernet (rev 20)
02:00.0 Ethernet controller: Broadcom Corporation NetXtreme II BCM5709 Gigabit Ethernet (rev 20)
02:00.1 Ethernet controller: Broadcom Corporation NetXtreme II BCM5709 Gigabit Ethernet (rev 20)`
Pulled from `lspci` on Pygmalion, we're not using a QLogic NIC.

2017-10-17 08:29 UTC, CSmartt commented on docs/hardware/pygmalion.md
> +* Network: QLogic bnx2 Gigabit Ethernet Driver v2.2.6
Also, 4 of these ^^^

2017-10-18 17:49 UTC, Sangreal8 commented on docs/hardware/pygmalion.md
> +* Network: QLogic bnx2 Gigabit Ethernet Driver v2.2.6
Thanks! :)

2017-10-22 18:29 UTC, CSmartt approved these changes

2017-10-22 19:00 UTC, merged