Update to docker logging and routeings
redbrick/docs-old pull request #90
Opened 2018-04-14 13:36 UTC by butlerx

**add** traefik
add elasticsearch
add procedures for adding a docker server

2018-04-14 13:46 UTC, VoyTechnology requested changes

2018-04-14 13:46 UTC, VoyTechnology commented on docs/hardware/zeus.md
> +[docs](../procedures/docker-serivce)
`docker-service`?

2018-04-14 13:46 UTC, VoyTechnology commented on docs/procedures/docker-service.md
> +traditional location such as `/ect/$SERIVCE_NAME` or `/var/lib/$SERVICE_NAME`
`ect` -> `etc`

2018-04-17 18:07 UTC, theycallmemac submitted a review, later dismissed

2019-02-26 22:50 UTC, m1cr0man submitted a review, later dismissed
Looks good. I'm just not sure about keeping copies of the docker-compose and config files in the docs. It seems like an unnecessary duplication of data, and more work for admins updating those files to deal with. I think pointing to their location on disk would be suffice.

2019-02-26 22:50 UTC, m1cr0man commented on docs/monitoring/elastic.md
> +docker-compose.yml
I don't think it's a great idea to put the configs in the docs. Simply pointing an admin to their location on a server would be sufficient and it means we aren't counting on admins to update 2 places.

2019-02-27 10:28 UTC, butlerx commented on docs/monitoring/elastic.md
> +docker-compose.yml
this was placed here more of an incase the server is lost.

what is actually needed is an eternal repo of the docker services compose files.

2019-09-06 13:31 UTC, theycallmemac commented on docs/monitoring/elastic.md
> +docker-compose.yml
@butlerx docker-compose configs on Redbrick have been made redundant privately on Github. If you remove configs I'd be happy to merge!

2019-09-06 13:42 UTC, butlerx commented on docs/monitoring/elastic.md
> +docker-compose.yml
this pr is outdated now since @m1cr0man 	deprecated es. i imagine the docker service and traefik info is partially right. @m1cr0man 	shall we remove the es part, or merge and remove with `tick` stack info?

2019-09-06 13:45 UTC, theycallmemac commented on docs/monitoring/elastic.md
> +docker-compose.yml
I would say remove the es part and then we can further add the tick info.

2019-09-07 14:01 UTC, theycallmemac commented
Any reason why a lot of the docs under `legacy` have been deleted in this PR? @butlerx

2019-09-07 14:12 UTC, butlerx commented
they were meant to have been deleted a while ago. in favour of using git history. we kept them around to ensure everything that was needed was pulled out before deleting. with rb-ldap changes being merged in im confident this pr encompasses the final clean up of the repo and update to state of my last interaction with the stack.

2019-09-09 10:59 UTC, theycallmemac commented
In this case I'd say remove what you have on ES and we can add the tick information in a separate PR.

2019-09-09 11:01 UTC, m1cr0man commented
Spoke to Cian about this IRL. I think it makes sense to merge this as-is and when I write the docs on TICK I will deprecate the old monitoring info.

2019-09-09 11:01 UTC, m1cr0man commented
Sorry...I wrote that and forgot part of my point. It's sensible to keep for historical records of the infra.

2019-09-09 13:17 UTC, theycallmemac commented
That is a good point. To have an account of past infra is important. We happy to merge this then?

2019-09-09 15:34 UTC, m1cr0man commented
Go for it :+1:

2019-09-09 15:34 UTC, merged