updating docker-compose
redbrick/docs-old pull request #97
Opened 2019-05-03 20:01 UTC by theycallmemac

docs are now ran in a container, so just adding relevant changes made to the repo.

2019-05-03 20:27 UTC, m1cr0man commented
You need to add the following info to the docker-compose.yml:
- restart: always
- The logging config (see mysql_repl)
- The traefik config (which involves adding the "web" external network to the container. See monitoring_tick chronograf service. You do not need the default network).

2019-05-03 20:29 UTC, m1cr0man requested changes

2019-05-03 20:29 UTC, m1cr0man commented on docker-compose.yml
> +      - /site:/site
If this is a relative path, use `./site` instead of just `/site`

2019-06-13 15:37 UTC, merged

2019-06-13 16:19 UTC, theycallmemac commented
Just for anyone who comes by this - it's a dev container, what m1cr0man was describing was our production container of this repository.